books_archive/urls.py
from django.contrib import admin
from django.urls import path,include
from records import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'',views.book_list,name='book_list'),
    path(r'',include('records.urls'))
]

records/urls.py
from django.urls import path,re_path
from records import views

app_name='records'

urlpatterns = [

    re_path(r'^books/create/$',views.bookcreate,name='create'),
    re_path(r'^books/(?P<pk>\d+)/update/$',views.book_update,name='book_update'),
    re_path(r'^books/(?P<pk>\d+)/delete/$',views.book_delete,name='book_delete'),

]

records/models.py
from django.db import models

# Create your models here.
class Book(models.Model):
    READ = 1
    UNREAD = 2
    READING = 3
    BOOK_STATUS = (
        (READ, 'Read'),
        (UNREAD, 'Unread'),
        (READING,'Reading'),
    )

    REVIEW = (
        ('Good','Good'),
        ('Fair','Fair'),
        ('Bad','Bad'),
    )
    user=models.ForeignKey('auth.user',on_delete=models.CASCADE,default="")
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=30, blank=True)
    pages = models.IntegerField(blank=True, null=True)
    review = models.CharField(choices=REVIEW,max_length=4)
    book_status = models.PositiveSmallIntegerField(choices=BOOK_STATUS)

    def __str__(self):
        return self.title +' '+ 'by' +' '+ self.author

records/forms.py
from django import forms
from .models import Book

class BookForm(forms.ModelForm):
	class Meta:
		model=Book
		fields=('title','author','pages','book_status','review')

records/views.py
from django.shortcuts import render,get_object_or_404 
from django.http import JsonResponse
from django.template.loader import render_to_string
from .models import Book
from .forms import BookForm
from django.contrib.auth.models import User
# Create your views here.
def book_list(request):
	books=Book.objects.filter(user=request.user)
	context={'books':books}
	return render(request,'records/book_list.html',context)

def save_book_form(request, form, template_name):
    data = dict()
    if request.method == 'POST':
        if form.is_valid():
            book = form.save(commit=False)
            book.user=request.user
            book.save()
            data['form_is_valid'] = True
            books = Book.objects.filter(user=request.user)
            data['html_book_list'] = render_to_string('records/partial_book_list.html', {'books': books})
        else:
            data['form_is_valid'] = False
    context = {'form': form}
    data['html_form'] = render_to_string(template_name, context, request=request)
    return JsonResponse(data)


def bookcreate(request):
    if request.method == 'POST':
        form = BookForm(request.POST)
    else:
        form = BookForm()
    return save_book_form(request, form, 'records/book_create.html')


def book_update(request,pk):
    book = get_object_or_404(Book, pk=pk)
    if request.method == 'POST':
        form = BookForm(request.POST, instance=book)
    else:
        form = BookForm(instance=book)
    return save_book_form(request, form, 'records/partial_book_update.html')

def book_delete(request,pk):
    book = get_object_or_404(Book,pk=pk)
    data = dict()
    if request.method == 'POST':
        book.delete()
        data['form_is_valid'] = True  # This is just to play along with the existing code
        books = Book.objects.filter(user=request.user)
        data['html_book_list'] = render_to_string('records/partial_book_list.html', {'books': books})
    else:
        context = {'book': book}
        data['html_form'] = render_to_string('records/partial_book_delete.html',context,request=request,)
    return JsonResponse(data)

records/templates/records/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Books Archive</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-inverse">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#main-menu" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="{% url 'book_list' %}">MY BOOK ARCHIVE</a>
        </div>
        <div class="collapse navbar-collapse" id="main-menu">
          <ul class="nav navbar-nav">
            {% url 'book_list' as book_list %}
            <li {% if request.path == book_list %} class='active'{% endif %}>
              <a href="">Books</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>  
    <div class="container">
      {% block content %}
      {% endblock %}
    </div>
    <script src="https://code.jquery.com/jquery-3.1.1.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>    
    {% block javascript %}
    {% endblock %}
  </body>
</html>

records/templates/records/book_create.html
{% load widget_tweaks %}

<form method="post" action="{% url 'records:create' %}" class="js-book-create-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Create a new book</h4>
  </div>
  <div class="modal-body">
     {% include 'records/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Create book</button>
  </div>
</form>

records/templates/records/book_list.html
{% extends 'records/base.html' %}

{% load static %}

{% block javascript %}
  <script src="{% static 'records/js/books.js' %}"></script>
{% endblock %}

{% block content %}
  <h1 class="page-header">Books</h1>

  <!-- BUTTON TO TRIGGER THE ACTION -->
  <p>
    <button type="button" class="btn btn-primary js-create-book" data-url="{% url 'records:create' %}">
      <span class="glyphicon glyphicon-plus"></span>
      New book
    </button>
  </p>

  <table class="table" id="book-table">
    <thead>
      <tr>
        <th>S/N</th>
        <th>Title</th>
        <th>Author</th>
        <th>Pages</th>
        <th>Book Status</th>
        <th>Review</th>
      </tr>
    </thead>
    <tbody>
      {% include 'records/partial_book_list.html' %}
    </tbody>
  </table>
   <!-- THE MODAL WE WILL BE USING -->
  <div class="modal fade" id="modal-book">
    <div class="modal-dialog">
      <div class="modal-content">
      </div>
    </div>
{% endblock %}

records/templates/records/partial_book_delete.html
<form method="post" action="{% url 'records:book_delete' book.id %}" class="js-book-delete-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Confirm book deletion</h4>
  </div>
  <div class="modal-body">
    <p class="lead">Are you sure you want to delete the book <strong>{{ book.title }}</strong>?</p>
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-danger">Delete book</button>
  </div>
</form>

records/templates/records/partial_book_form.html
{% load widget_tweaks %}

{% for field in form %}
  <div class="form-group{% if field.errors %} has-error{% endif %}">
    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
    {% render_field field class="form-control" %}
    {% for error in field.errors %}
      <p class="help-block">{{ error }}</p>
    {% endfor %}
  </div>
{% endfor %}

records/templates/records/partial_book_list.html
  {% for book in books %}
    <tr>
      <td>{{ book.id }}</td>
      <td>{{ book.title }}</td>
      <td>{{ book.author }}</td>
      <td>{{ book.pages}}</td>
      <td>{{ book.get_book_status_display }}</td>
      <td>{{ book.review }}</td>
      <td>
        <button type="button" class="btn btn-warning js-book-update" data-url="{% url 'records:book_update' book.id %}">
          <span class="glyphicon glyphicon-pencil"> Edit</span>
        </button>
        <button type="button" class="btn btn-danger js-book-delete" data-url="{% url 'records:book_delete' book.id %}">
          <span class="glyphicon glyphicon-trash"> Delete</span>
        </button>
      </td>
    </tr>
  {% empty %}
    <tr>
      <td colspan="7" class="text-center bg-warning">No book</td>
    </tr>
  {% endfor %}

records/templates/records/partial_book_update.html
<form method="post" action="{% url 'records:book_update' form.instance.pk %}" class="js-book-update-form">
  {% csrf_token %}
  <div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    <h4 class="modal-title">Update book</h4>
  </div>
  <div class="modal-body">
    {% include 'records/partial_book_form.html' %}
  </div>
  <div class="modal-footer">
    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
    <button type="submit" class="btn btn-primary">Update book</button>
  </div>
</form>